project_id = "krqxzxhqjkpimscufxnc"

[functions.export-database]
verify_jwt = false

[functions.rubrica-analysis]
verify_jwt = false

[functions.github-commits]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-executive-summary]
verify_jwt = false