
CREATE TABLE public.fichas_rlt (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  acepta_datos BOOLEAN NOT NULL DEFAULT false,
  nombres_apellidos TEXT NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  lengua_materna TEXT NOT NULL DEFAULT 'Español',
  lengua_otra TEXT,
  celular_personal TEXT NOT NULL,
  correo_personal TEXT NOT NULL,
  correo_institucional TEXT,
  prefiere_correo TEXT NOT NULL,
  enfermedad_base TEXT NOT NULL DEFAULT 'No',
  enfermedad_detalle TEXT,
  contacto_emergencia TEXT,
  telefono_emergencia TEXT,
  discapacidad TEXT NOT NULL DEFAULT 'No',
  discapacidad_detalle TEXT,
  tipo_formacion TEXT,
  titulo_pregrado TEXT,
  titulo_especializacion TEXT,
  titulo_maestria TEXT,
  titulo_doctorado TEXT,
  otros_titulos TEXT,
  region TEXT NOT NULL,
  nombre_ie TEXT NOT NULL,
  cargo_actual TEXT NOT NULL,
  tipo_vinculacion TEXT,
  fecha_vinculacion_servicio DATE,
  fecha_nombramiento_cargo DATE,
  fecha_nombramiento_ie DATE,
  estatuto TEXT,
  grado_escalafon TEXT,
  codigo_dane TEXT,
  entidad_territorial TEXT,
  comuna_barrio TEXT,
  zona_sede TEXT,
  total_sedes INTEGER,
  sedes_rural INTEGER,
  sedes_urbana INTEGER,
  jornadas TEXT[],
  grupos_etnicos TEXT,
  proyectos_transversales TEXT,
  estudiantes_jec INTEGER,
  desplazamiento TEXT,
  niveles_educativos TEXT[],
  tipo_bachillerato TEXT,
  modelo_pedagogico TEXT,
  num_docentes INTEGER,
  num_coordinadores INTEGER,
  num_administrativos INTEGER,
  num_orientadores INTEGER,
  estudiantes_preescolar INTEGER,
  estudiantes_primaria INTEGER,
  estudiantes_ciclo_complementario INTEGER,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.fichas_rlt ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción pública" ON public.fichas_rlt FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir lectura pública" ON public.fichas_rlt FOR SELECT USING (true);
